# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Aaron Heuckroth
tagline:          'code, 3D printing, music, etc.'
description:      ''
url:              http://heuckroth.com

author:
  name:           'Aaron Heuckroth'
  url:            https://twitter.com/Nesciosquid
paginate:         5

gems:             [jekyll-paginate]

github:
  repo:           https://github.com/Nesciosquid
