# Permalinks
permalink:        pretty

# Setup
title:            Aaron Heuckroth
tagline:          'code, 3D printing, music, etc.'
description:      ''
url:              www.heuckroth.com

author:
  name:           'Aaron Heuckroth'
  url:            https://twitter.com/Nesciosquid
paginate:         5

gems:             [jekyll-paginate]