# Permalinks
permalink:        pretty

# Setup

author:
  name: Aaron Heuckroth
  url:  http://www.heuckroth.com
  email:  aaron@heuckroth.com
  twitter: Nesciosquid
  
name: heuckroth.com
title: Aaron Heuckroth
tagline: (Nesciosquid)
description: Thoughts on code, 3D printing, music, and more.
baseurl: ""
url: http://www.heuckroth.com
twitter_username: Nesciosquid
github_username: Nesciosquid

jekyll-archives:
  enabled: ['categories', 'tags']
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

feed:
  path: atom.xml
  
paginate:         1

twitter:
    username: Nesciosquid

gems:      
- jekyll-archives       
- jekyll-paginate
- jekyll-gist
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap