# Permalinks
permalink:        pretty

# Setup
title:            Aaron Heuckroth
tagline:          '(Nesciosquid)'
description:      'Thoughts on code, 3D printing, music, and more.'
url:              http://www.heuckroth.com/

feed: 
  path: atom.xml

author:
  name:           Aaron Heuckroth
  url:            http://www.heuckroth.com/
  uri:            http://www.heuckroth.com/about/
  email:          aaron@heuckroth.com

paginate:         5

twitter:
    username: Nesciosquid

gems:             
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed