# Permalinks
permalink:        pretty

# Setup

author:
  name: Aran Ink
  url:  https://nesciosquid.github.io/
  twitter: nesciosquid
  
name: nesciosquid.github.io
title: Aran P. Ink
tagline: (Nesciosquid)
description: Thoughts on code, 3D printing, music, and more.
baseurl: ""
url: https://nesciosquid.github.io
twitter_username: nesciosquid
github_username: nesciosquid

jekyll-archives:
  enabled: ['categories', 'tags']
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

feed:
  path: atom.xml
  
paginate:         1

twitter:
    username: nesciosquid

gems:      
- jekyll-archives       
- jekyll-paginate
- jekyll-gist
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
