# Permalinks
permalink:        pretty

# Setup
name: heuckroth.com
title: Aaron Heuckroth
tagline: (Nesciosquid)
description: Thoughts on code, 3D printing, music, and more.
baseurl: ""
url: http://www.heuckroth.com
twitter_username: Nesciosquid
github_username: Nesciosquid

feed:
  path: atom.xml

author:
  name:           'Aaron Heuckroth'
  url:            http://www.heuckroth.com
  email:          aaron@heuckroth.com

paginate:         1

twitter:
    username: Nesciosquid

gems:             
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed